### PR TITLE
Parallel

### PR DESCRIPTION
**Pull request by mtbentley**
Things work.  Mostly pull-requesting for review and testing.

### CODE REVIEW

**Comment by ajm188** [comment]
Everything in here looks fine. What's the error that you're getting for the qos=1 ?

**Comment by mtbentley** [comment]
This seems to fix the issue with qos=1 (and maybe 2, haven't got around to that).  And it turns out there are errors (timeouts ~9% of the time) that I wasn't catching because I forgot that if I set the timeout to 10 min it will take 10 min before timeout errors start showing up.

**Comment by mtbentley** [comment]
And with qos=1 I'm currently getting 0 errors (maybe, unless I'm missing something)

**Comment by ajm188** [comment]
I am seeing this working for qos=1, so :+1:

**Pull request merged**
